version: "3"

services:
  nuxtjs:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./tuinautomatisatieV4:/home/node/app
    expose:
      - "3000"
    command: "npm run dev"

    ports: 
      - "8082:3000"
    restart: unless-stopped